basePath: /
definitions:
  handlers.AuthRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  handlers.AuthResponse:
    properties:
      expires_at:
        type: string
      token:
        type: string
      user:
        $ref: '#/definitions/handlers.UserResponse'
    type: object
  handlers.UserResponse:
    properties:
      id:
        type: string
      is_admin:
        type: boolean
      login:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: API для авторизації користувачів
  title: Auth Service API
  version: "1.0"
paths:
  /api/auth:
    post:
      consumes:
      - application/json
      description: Приймає логін і пароль, перевіряє користувача та повертає JWT токен
      parameters:
      - description: Дані користувача
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "400":
          description: Некоректний запит
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Невірні дані
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Помилка сервера
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Авторизація користувача
      tags:
      - auth
  /auth/validate:
    get:
      description: Перевіряє дійсність JWT токена
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Invalid token
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Валідація токена
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
